<?php

namespace Todo\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TodoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoListRepository extends EntityRepository
{
}
